# -*- coding: utf-8 -*-
"""qonfido_test_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Y0p-yFGZuMWm6mCbBJSUw32R82fYpP9
"""

# ============================================
# BLOCK 1 – Import Libraries
# ============================================

import pandas as pd
from datetime import datetime

# ============================================
# BLOCK 2 – Load Excel File
# ============================================

file_path = "/content/Monthly Portfolio-31 12 25.xlsx"
xls = pd.ExcelFile(file_path)

print("Total Sheets Found:", len(xls.sheet_names))
print("Sheet Names:", xls.sheet_names)

# ============================================
# BLOCK 3 – Initialize Storage
# ============================================

all_data = []

"""#============================================
# BLOCK 4 – Parse & Clean Each Sheet
# ============================================
"""

for sheet in xls.sheet_names:
    if sheet.lower() == "index":
        continue

    df = pd.read_excel(file_path, sheet_name=sheet, header=3)

    # Rename unnamed first column
    if "Unnamed: 0" in df.columns:
        df.rename(columns={"Unnamed: 0": "instrument_code"}, inplace=True)

    # Remove fully empty rows
    df.dropna(how="all", inplace=True)

    # Convert quantity to numeric FIRST
    if "Quantity" not in df.columns:
        continue

    df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

    # ✅ STRICT FILTER: Keep ONLY rows with BOTH valid instrument_code AND Quantity
    df = df[
        (df["instrument_code"].notna()) &
        (df["Quantity"].notna()) &
        (df["Quantity"] > 0)
    ].copy()

    # Skip sheets with no valid data
    if len(df) == 0:
        continue

    # Add metadata ONLY to clean rows
    df["scheme_name"] = sheet
    df["amc_name"] = "Axis Mutual Fund"
    df["reporting_date"] = datetime(2025, 12, 31)

    all_data.append(df)

print(f"\n✅ Processed {len(all_data)} sheets")

"""#
# ============================================
# BLOCK 5 – Consolidate Data
# ============================================
"""

final_df = pd.concat(all_data, ignore_index=True)
print(f"✅ Total Records: {len(final_df)}")

"""# ============================================
# BLOCK 6 – Data Type Standardization
# ============================================
"""

final_df["Market/Fair Value\n (Rs. in Lakhs)"] = pd.to_numeric(
    final_df["Market/Fair Value\n (Rs. in Lakhs)"], errors="coerce"
)

final_df["% to Net\n Assets"] = pd.to_numeric(
    final_df["% to Net\n Assets"], errors="coerce"
)

"""# ============================================
# BLOCK 7 – Column Name Cleaning
# ============================================

"""

final_df.columns = (
    final_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
    .str.replace("\n", "")
)

def classify_instrument(row):
    """Classify as Equity, Debt, or Other"""
    name = str(row.get('name_of_the_instrument', '')).lower()
    isin = str(row.get('isin', '')).lower()

    # Debt indicators
    debt_keywords = ['government', 'treasury', 'bond', 'debenture', 'commercial paper',
                     'certificate of deposit', 'repo', 'tbill', 'g-sec']
    if any(keyword in name for keyword in debt_keywords):
        return 'Debt'

    # Equity indicators (equity ISINs start with INE)
    if isin.startswith('ine') and 'eq' in isin:
        return 'Equity'

    # Check industry/rating column for equity sectors
    industry = str(row.get('industry___rating', '')).lower()
    equity_sectors = ['technology', 'pharma', 'fmcg', 'banking', 'auto', 'telecom']
    if any(sector in industry for sector in equity_sectors):
        return 'Equity'

    return 'Other'

final_df['instrument_type'] = final_df.apply(classify_instrument, axis=1)

"""# **BLOCK 8 – Export Output**



"""

final_df.to_csv("consolidated_portfolio.csv", index=False)
print("✅ CSV Generated Successfully")

"""# **BLOCK 9 – Preview Output**"""

print("\n=== FIRST 5 ROWS ===")
print(final_df.head())

print("\n=== DATA INFO ===")
print(final_df.info())

"""# **BLOCK 10 – Verification Check**"""

print("\n=== VERIFICATION ===")
print(f"Rows with missing instrument_code: {final_df['instrument_code'].isna().sum()}")
print(f"Rows with missing quantity: {final_df['quantity'].isna().sum()}")
print(f"Rows with quantity <= 0: {(final_df['quantity'] <= 0).sum()}")